### ISSUE TITLE
Missing grid-rnn

### ISSUE THREAD

**Issue by indiejoseph** [phvu/grid-lstm-tensorflow#1]
Where did you get the `grid-rnn` library for `tensorflow`?

**Comment by phvu** [comment]
I am working on it. Will submit a PR to `tensorflow` once I am done with testing. Tentatively next week.

**Comment by indiejoseph** [comment]
Good to hear that more people becoming tensorflow's contributor, great job man!

**Comment by Yc174** [comment]
Thanks for your work! I have read your code and test for grid_lstm, but still dont  know how to code for it. Can you release a code for mnist dataset use grid lstm?

**Comment by Yc174** [comment]
@phvu
